import Immutable from 'seamless-immutable';

export const stations = Immutable({
  '12th': '12th St. Oakland City Center',
  '16th': '16th St. Mission (SF)',
  '19th': '19th St. Oakland',
  '24th': '24th St. Mission (SF)',
  'ashb': 'Ashby (Berkeley)',
  'balb': 'Balboa Park (SF)',
  'bayf': 'Bay Fair (San Leandro)',
  'cast': 'Castro Valley',
  'civc': 'Civic Center (SF)',
  'colm': 'Colma',
  'cols': 'Coliseum',
  'conc': 'Concord',
  'daly': 'Daly City',
  'dbrk': 'Downtown Berkeley',
  'deln': 'El Cerrito del Norte',
  'dubl': 'Dublin/Pleasanton',
  'embr': 'Embarcadero (SF)',
  'frmt': 'Fremont',
  'ftvl': 'Fruitvale (Oakland)',
  'glen': 'Glen Park (SF)',
  'hayw': 'Hayward',
  'lafy': 'Lafayette',
  'lake': 'Lake Merritt (Oakland)',
  'mcar': 'MacArthur (Oakland)',
  'mlbr': 'Millbrae',
  'mont': 'Montgomery St. (SF)',
  'nbrk': 'North Berkeley',
  'ncon': 'North Concord/Martinez',
  'oakl': 'Oakland Intl Airport',
  'orin': 'Orinda',
  'phil': 'Pleasant Hill',
  'pitt': 'Pittsburg/Bay Point',
  'plza': 'El Cerrito Plaza',
  'powl': 'Powell St. (SF)',
  'rich': 'Richmond',
  'rock': 'Rockridge (Oakland)',
  'sanl': 'San Leandro',
  'sbrn': 'San Bruno',
  'sfia': 'San Francisco Intl Airport',
  'shay': 'South Hayward',
  'ssan': 'South San Francisco',
  'ucty': 'Union City',
  'warm': 'Warm Springs/South Fremont',
  'wcrk': 'Walnut Creek',
  'wdub': 'West Dublin',
  'woak': 'West Oakland',
});

export const cmd = Immutable({
  arrive: 'arrive',
  depart: 'depart',
});
